### ISSUE TITLE
Create server button does nothing?

### ISSUE THREAD

**Issue by 1101-trash** [Amenofisch/MultiBazou#1]
I got the mod working but sadly the "Create Server" button appearently does nothing. I also don't know how to close and open the menu.
Please if you continue working on this mod it'd be amazing, lot of people are waiting for enjoy mon bazou with friends :D

**Comment by Amenofisch** [comment]
Hey there, the "Create Server"-Button actually does do something, there is just no feedback without opening the BepInEx console. 
Also there currently is no button to close the menu.

**Comment by 1101-trash** [comment]
Oh! Thanks for the reply & reply speed!! So my friend might just connect to me and we are all good?. Also there isnt any way to hide the menu?

**Comment by 1101-trash** [comment]
I manage to join my friend, he appear on my world but frozen and hes on his game anyway, also I get to his screen but I disappear and my game still normally

**Comment by 1101-trash** [comment]
And now it doesnt work, I was be able to see my friend moving but he was still in his "world"

**Comment by Amenofisch** [comment]
Multiplayer still doesn't work as it already says in the readme.
There is no synchronisation of worlds and of any objects.

**Comment by 1101-trash** [comment]
> Multiplayer still doesn't work as it already says in the readme. There is no synchronisation of worlds and of any objects.

Oh I understand. Thank you for replying and I hope you can work on this!
Wish you all the best! <3
